config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :teams
  resources :tournaments
  resources :organizations
  get "/", to: "pages#index", as: :home
  get "/terms", to: "pages#terms", as: :terms
  get "/privacy", to: "pages#privacy", as: :privacy
  get "/pricing", to: "pages#pricing", as: :pricing

  resources :users
  get "profile", to: "user#profile", as: :user_profile
  get "settings", to: "user#settings", as: :user_settings
  get "settings/profile", to: "user#settings_profile", as: :user_settings_profile
  get "settings/security", to: "user#settings_security", as: :user_settings_security
  get "settings/notifications", to: "user#settings_notifications", as: :user_settings_notifications
  patch "settings/update_profile", to: "user#update_profile", as: :update_profile
  patch "settings/update_notifications", to: "user#update_notifications", as: :update_notifications

  resource :registration, only: %i[ new create ]
  resource :session
  get "passwords/signed_in/edit", to: "passwords#signed_in_edit", as: :signed_in_edit_password
  patch "passwords/signed_in/update", to: "passwords#signed_in_update", as: :signed_in_update_password
  resources :passwords, param: :token, only: [ :new, :create, :edit, :update ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_with(model: organization, class: "contents") do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
        <% organization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :account_id %>
    <%= form.text_field :account_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/organizations/_organization.html.erb
<div id="<%= dom_id organization %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= organization.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Account:</strong>
    <%= organization.account_id %>
  </p>

</div>

app/views/organizations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing organization</h1>

  <%= render "form", organization: @organization %>

  <%= link_to "Show this organization", @organization, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to organizations", organizations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/organizations/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Organizations" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Organizations</h1>
    <%= link_to "New organization", new_organization_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="organizations" class="min-w-full">
    <% @organizations.each do |organization| %>
      <%= render organization %>
      <p>
        <%= link_to "Show this organization", organization, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/organizations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New organization</h1>

  <%= render "form", organization: @organization %>

  <%= link_to "Back to organizations", organizations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/organizations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @organization %>

    <%= link_to "Edit this organization", edit_organization_path(@organization), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to organizations", organizations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this organization", @organization, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>